site_name: hudascraper
nav:
  - Home: index.md
  - API: api.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.insert(0, '.')
theme:
  name: material
